### ISSUE TITLE
Yahoo Oauth issue - Cycle Prohibited

### ISSUE THREAD

**Issue by njt28** [FuckBoilerplate/RxSocialConnect-Android#5]
Hi there,

Thanks for your great library!!
I'm having a problem with Yahoo oauth code.
The webview is displaying with a message:
Description: Could not process your request for the document because it would cause an HTTP proxy cycle.  Please check the URL and your browser's proxy settings.

Please, any help? 

Thanks in advance.

**Comment by miguelbcr** [comment]
Hi @njt28,
maybe it is related with your proxy setting on your wifi setting, set proxy to none in order to ensure you are not using any proxy. 

I've just upload an example with [yahoo connection](https://github.com/FuckBoilerplate/RxSocialConnect-Android/commit/299f9e6db4f4cc7f2c977fe233f488a474824cd7). 

It works fine.
I hope it helps you.

**Comment by njt28** [comment]
Thanks @miguelbcr 
maybe it's related with Yahoo server rather than wifi settings.
Found many questions about it but no solution yet.

anyway, thanks for your anwser!!
